/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppGatewayRouteImport } from './routes/_app.gateway'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppAiSettingsRouteImport } from './routes/_app.ai-settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppGatewayRoute = AppGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSettingsRoute = AppAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai-settings': typeof AppAiSettingsRoute
  '/crm': typeof AppCrmRoute
  '/gateway': typeof AppGatewayRoute
  '/invoices': typeof AppInvoicesRoute
}
export interface FileRoutesByTo {
  '/ai-settings': typeof AppAiSettingsRoute
  '/crm': typeof AppCrmRoute
  '/gateway': typeof AppGatewayRoute
  '/invoices': typeof AppInvoicesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-settings': typeof AppAiSettingsRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/gateway': typeof AppGatewayRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-settings' | '/crm' | '/gateway' | '/invoices'
  fileRoutesByTo: FileRoutesByTo
  to: '/ai-settings' | '/crm' | '/gateway' | '/invoices' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ai-settings'
    | '/_app/crm'
    | '/_app/gateway'
    | '/_app/invoices'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gateway': {
      id: '/_app/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof AppGatewayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-settings': {
      id: '/_app/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AppAiSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiSettingsRoute: typeof AppAiSettingsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppGatewayRoute: typeof AppGatewayRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiSettingsRoute: AppAiSettingsRoute,
  AppCrmRoute: AppCrmRoute,
  AppGatewayRoute: AppGatewayRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
