/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppAiSettingsRouteImport } from './routes/_app.ai-settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSettingsRoute = AppAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai-settings': typeof AppAiSettingsRoute
  '/crm': typeof AppCrmRoute
}
export interface FileRoutesByTo {
  '/ai-settings': typeof AppAiSettingsRoute
  '/crm': typeof AppCrmRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-settings': typeof AppAiSettingsRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-settings' | '/crm'
  fileRoutesByTo: FileRoutesByTo
  to: '/ai-settings' | '/crm' | '/'
  id: '__root__' | '/_app' | '/_app/ai-settings' | '/_app/crm' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-settings': {
      id: '/_app/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AppAiSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiSettingsRoute: typeof AppAiSettingsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiSettingsRoute: AppAiSettingsRoute,
  AppCrmRoute: AppCrmRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
